name: Tests
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16      
      - name: Check out source code
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false      
      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .
      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v
